name: Fetch & Update data (No Student List)

# Schedual the workflow to run every day at 18:00 UTC+8
# between add and drop period (2024/02/14-2024/02/29)
# fetch data with student list from the website and update the database
on:
  schedule:
    # Fetch data Every days at 04:00 UTC+8
    # between 2024/09/04-2024/09/18 (After add & drop period)
    - cron: '0 4 14-31 10 2'
    - cron: '0 4 1-16 11 2'
    - cron: '0 4 16-30 11 *'
  push:

jobs:
  Fetch:
    runs-on: ubuntu-22.04
    steps:
      
      - name: Install git
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get -y install git
      - uses: actions/checkout@v4

      - name: copy last data from api branch
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch 
          git checkout main
          git restore --source  origin/api api/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch data
        run: |
          cd src
          python fetch_all_without_stu_list.py

      - name: Generate output folder
        run: |
          mkdir output
          cp -r api output/api

      # Push the updated 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: api
          commit_message: "Update api data"
