name: Fetch & Update data

# Schedual the workflow to run every day at 18:00 UTC+8
# between add and drop period (2024/02/14-2024/02/29)
# fetch data with student list from the website and update the database
# on:
  # schedule:
  #   - cron: '0 10 2 14-29 *'
on:
  push:
    branches:
      - main

jobs:
  Fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy last data from api branch
        run: | 
          pwd
          git restore --source api api/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch data
        run: |
          cd src
          python test.py

      # Push the updated 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api
          publish_branch: api
          force_orphan: true
          clean: true
          commit_message: "Update api data"
