name: Fetch & Update data (No Student List)

# Schedual the workflow to run every day at 18:00 UTC+8
# between add and drop period (2024/02/14-2024/02/29)
# fetch data with student list from the website and update the database
on:
  schedule:
    # Fetch data Every 7 days at 04:00 UTC+8
    # between 2024/03/07-2024/03/31 (After add & drop period)
    - cron: '0 20 6-31/7 3 *'
    # Fetch data Every 5 days  at 04:00 UTC+8
    # between 2024/04/01-2024/05/10 (期中退選)
    - cron: '0 20 */5 4 *'
    - cron: '0 20 1-10/5 5 *'
    - cron: '0 20 10 5 *'
    # Fetch data Every 2 days at 04:00 UTC+8
    # between 2024/05/11-2024/05/23 (before preselect next semester)
    - cron: '0 20 11-23/7 5 *'
    - cron: '0 20 23 5 *'
  push:
    branches:
      - main
jobs:
  Fetch:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install git
        run: |
          sudo apt-get -y install git

      - name: copy last data from api branch
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch 
          git checkout main
          git restore --source  origin/api api/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch data
        run: |
          cd src
          python fetch_all_without_stu_list.py

      - name: Generate output folder
        run: |
          mkdir output
          cp -r api output/api

      # Push the updated 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: api
          commit_message: "Update api data"
