name: Fetch & Update data

# Schedual the workflow to run every day at 18:00 UTC+8
# between add and drop period (2024/02/14-2024/02/29)
# fetch data with student list from the website and update the database
on:
  schedule:
    # Fetch data every day at 22:00 UTC+8
    # Every 2 days between 2024/02/10-2024/02/13 (Before add & drop period)
    - cron: '0 14 10-13/2 2 *'
    # Fetch data every day at 22:00 UTC+8
    # Every 5 days between 2024/03/07-2024/03/31 (After add & drop period)
    - cron: '0 14 7-31/5 3 *'
    # Fetch data every day at 22:00 UTC+8
    # Every 2 days between 2024/04/01-2024/05/10 (期中退選)
    - cron: '0 14 */2 4 *'
    - cron: '0 14 1-10/2 5 *'
    - cron: '0 14 10 5 *'
    # Fetch data every day at 22:00 UTC+8
    # Every 2 days between 2024/05/11-2024/05/23 (preselect next semester)
    - cron: '0 14 11-23/2 5 *'
jobs:
  Fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy last data from api branch
        run: |
          files=$(find $SRC_FOLDER_PATH -type f) # get the file list
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch 
          git checkout main
          git restore --source  origin/api api/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch data
        run: |
          cd src
          python fetch_all_without_stu_list.py

      - name: Generate output folder
        run: |
          mkdir output
          cp -r api output/api

      # Push the updated 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: api
          commit_message: "Update api data"
